// <auto-generated />
using LaudoPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaudoPro.Migrations
{
    [DbContext(typeof(LaudoProDbContext))]
    [Migration("20251016204158_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LaudoPro.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Price = 29.899999999999999,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Price = 49.899999999999999,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Price = 69.900000000000006,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Price = 149.90000000000001,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Price = 199.90000000000001,
                            Type = 5
                        },
                        new
                        {
                            Id = 7,
                            Price = 299.89999999999998,
                            Type = 6
                        });
                });

            modelBuilder.Entity("LaudoPro.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
